version: '3.8'

services:
  web:
    build: .
    container_name: ctf5-php-injection
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
